Add support for crystal 1.2
Fixes #45

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -12,6 +12,11 @@ install_crystal() {
   local version=$2
   local install_path=$3
 
+  while IFS='.' read -ra SEMVER; do
+    major=${SEMVER[0]}
+    minor=${SEMVER[1]}
+  done <<< "$version";
+
   if [ "$install_type" != "version" ]; then
     fail "asdf-crystal supports release installs only"
   fi
@@ -24,13 +29,11 @@ install_crystal() {
     *) fail "Unsupported platform" ;;
   esac
 
-  local architecture
+  architecture="$(uname -m)"
 
-  case "$(uname -m)" in
-    x86_64) architecture="x86_64" ;;
-    i686) architecture="i686" ;;
-    *) fail "Unsupported architecture" ;;
-  esac
+  if [ "$platform" = "darwin" ] && [ "$major" -ge 1 ] && [ "$minor" -ge 2 ] ; then
+    architecture="universal"
+  fi
 
   local download_url="https://github.com/crystal-lang/crystal/releases/download/${version}/crystal-${version}-1-${platform}-${architecture}.tar.gz"
   local tmp_download_dir
@@ -39,7 +42,7 @@ install_crystal() {
 
   (
     echo "∗ Downloading and installing Crystal..."
-    curl --silent --fail --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download Crystal $version"
+    curl --silent --fail --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download Crystal $version for architecture $architecture"
     tar zxf "$source_path" -C "$install_path" --strip-components=1
     rm -rf "$tmp_download_dir"
 
